# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 265843d7c730ddabb55dcd6ee812cbe97d7ae010f0f52f34bbab241ff1712c1ac55f3f5a2b669901c172eade5e0a03978a28bbaddf2ccaa2cdabfb8389c7e539

test:
  secret_key_base: ed2cd7309deb5b4fef5c18fc4c1ab805c511ea61a7fcea6b3faca7541620171aae471a3d628343fbe8dc58b5cca7f04a18e25003f59236796b84a4531e0a5df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
